apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: tiredful
        image: natalieaoya/tiredful:latest
        securityContext:
            allowPrivilegeEscalation: false
        ports:
        - containerPort: 8000 

