name: CI/CD

on:
  push:
    branches:
      - main

jobs:        
  oast:
    runs-on: ubuntu-22.04    
    needs: test
    steps:
      - uses: actions/checkout@v4

      - run: docker run --rm -v $(pwd):/src hysnsec/safety check -r Tiredful-API-master/requirements.txt --json > oast-results.json
        continue-on-error: true

      - uses: actions/upload-artifact@v4
        with:
          name: Safety
          path: oast-results.json
        if: always()                    
