name: Django                                  # workflow name

on:
  push:
    branches:                                 # similar to "only" in GitLab
      - main

jobs:
  oast-safety:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - run: docker run --rm -v $(pwd):/src hysnsec/safety check -r Tiredful-API-master/requirements.txt --json > safety-results.json
        continue-on-error: true             

      - uses: actions/upload-artifact@v4
        with:
          name: Safety
          path: safety-results.json
        if: always()

  oast-snyk:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@master
      - uses: snyk/actions/setup@master
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - uses: actions/setup-node@v4
        with:
          node-version: '10.x'

      - name: Install Node modules
        run: npm install

      - name: Run Snyk
        run: snyk test --json > snyk-results.json
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true    

      - uses: actions/upload-artifact@v4
        with:
          name: Snyk
          path: snyk-results.json
        if: always() 
