name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          pip install -r Tiredful-API-master/requirements.txt
      
      - name: Run Safety
        run: |
          pip install safety
          safety check --full-report --output-format json > safety-report.json || true
      
      - name: Run Snyk
        uses: snyk/actions/python@master
        with:
          snyk-token: ${{ secrets.SNYK_TOKEN }}

      - name: Run SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        with:
          sonarsource-project-key: ${{ secrets.SONAR_PROJECT_KEY }}
          sonarsource-project-name: Tiredful
          sonarsource-organization: Natalie Aoya
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Docker Scout
        run: |
          docker scout cves my-image:latest --json > docker-scout-report.json || true

      - name: Upload Safety Report
        uses: actions/upload-artifact@v4
        with:
          name: safety-report
          path: safety-report.json

      - name: Upload Docker Scout Report
        uses: actions/upload-artifact@v4
        with:
          name: docker-scout-report
          path: docker-scout-report.json

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t natalieaoya/tiredful:latest .

      - name: Push Docker image
        run: |
          docker push natalieaoya/tiredful:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'
      
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
          kubectl rollout status deployment/my-deployment

