name: Tiredful

on:
  push:
    branches:                                
      - main

jobs:
  oast-safety:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - run: docker run --rm -v $(pwd):/src hysnsec/safety check -r requirements.txt --json > safety-results.json
        continue-on-error: true             

      - uses: actions/upload-artifact@v4
        with:
          name: Safety
          path: safety-results.json
        if: always()

  sast-snyk:
    runs-on: self-hosted
    needs: oast-safety
    steps:
      - name: Checkout the code
        uses: actions/checkout@master

      - name: Run Snyk
        uses: snyk/actions/python@master
        with:
          args: --json-file-output=snyk-results.json --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true    

      - uses: actions/upload-artifact@v4
        with:
          name: Snyk
          path: snyk-results.json
        if: always()

  sast-hadolint:
    runs-on: self-hosted
    needs: sast-snyk
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Hadolint
        uses: hadolint/hadolint-action@v3.1.0        
        with:
          dockerfile: Dockerfile
          failure-threshold: warning
          format: json
          output-file: hadolint.json
        continue-on-error: true

      - uses: actions/upload-artifact@v4
        with:
          name: Hadolint
          path: hadolint.json
        if: always()

  build:
    runs-on: self-hosted
    needs: sast-hadolint

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t natalieaoya/tiredful:latest .
          docker push natalieaoya/tiredful:latest

  image-scan:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout the code
        uses: actions/checkout@master

      - name: Run Snyk
        uses: snyk/actions/docker@master
        with:
          args: --json-file-output=image-scan.json --severity-threshold=high
          image: natalieaoya/tiredful:latest
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true    

      - uses: actions/upload-artifact@v4
        with:
          name: Image Scan
          path: image-scan.json
        if: always()


  deploy:
    runs-on: self-hosted
    needs: image-scan

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy on EC2
        run: |
            kubectl apply -f deployment.yaml
            kubectl apply -f service.yaml
