name: Django                                  # workflow name

on:
  push:
    branches:                                 # similar to "only" in GitLab
      - main

jobs:
  oast-safety:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - run: docker run --rm -v $(pwd):/src hysnsec/safety check -r Tiredful-API-master/requirements.txt --json > safety-results.json
        continue-on-error: true             

      - uses: actions/upload-artifact@v4
        with:
          name: Safety
          path: safety-results.json
        if: always()

  oast-snyk:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@master
      - uses: snyk/actions/setup@master
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python modules
        run: pip install -r Tiredful-API-master/requirements.txt

      - name: Run Snyk
        run: snyk code test --json-file-output=snyk-results.json --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true    

      - uses: actions/upload-artifact@v4
        with:
          name: Snyk
          path: snyk-results.json
        if: always()

  hadolint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Hadolint
        uses: hadolint/hadolint-action@v3.1.0        
        with:
          dockerfile: Tiredful-API-master/Dockerfile
          failure-threshold: warning
          format: json
          output-file: hadolint.json
        continue-on-error: true

      - uses: actions/upload-artifact@v4
        with:
          name: Hadolint
          path: hadolint.json
        if: always()

  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -f Tiredful-API-master/Dockerfile -t natalieaoya/tiredful:latest .
          docker push natalieaoya/tiredful:latest
