name: CI/CD

on:
  push:
    branches:
      - main

jobs:        
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - run: |
          pip3 install --upgrade virtualenv
          virtualenv env
          source env/bin/activate
          pip install -r Tiredful-API-master/requirements.txt

  oast:
    runs-on: ubuntu-22.04    
    needs: test
    steps:
      - uses: actions/checkout@v4

      - run: docker run --rm -v $(pwd):/src hysnsec/safety check -r requirements.txt --json > oast-results.json
        continue-on-error: true

      - uses: actions/upload-artifact@v4
        with:
          name: Safety
          path: oast-results.json
        if: always()                    
