name: CI/CD

on:
  push:
    branches:
      - main

jobs:        
  safety:
    runs-on: ubuntu-22.04    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Safety Check
        run: |
          mkdir -p safety-results
          docker run --rm -v $(pwd):/src hysnsec/safety check -r Tiredful-API-master/requirements.txt --json > safety-results/requirements-results.json
        continue-on-error: false

      - name: Run Safety Scan
        run: |
          docker run --rm -v $(pwd):/src hysnsec/safety scan . --save-as json safety-results/app-results.json
        continue-on-error: false

      - name: Upload Safety Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Safety
          path: safety-results/*
        if: always()  

