name: CI/CD

on:
  push:
    branches:
      - main

jobs:        
  safety:
    runs-on: ubuntu-22.04    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  

      - name: Install dependencies
        run: |
          pip install -r Tiredful-API-master/requirements.txt
          pip install safety   
   
      - name: Run Safety Check
        run: |
          mkdir -p safety-results
          safety check --save-json safety-results/requirements.json
        continue-on-error: false

      - name: Run Safety Scan
        run: |
          safety scan . --save-as json safety-results/app-results.json
        continue-on-error: false

      - name: Upload Safety Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Safety
          path: safety-results/*
        if: always()  

